import {counted,normalize,standings} from './logic.js';
const $ = id => document.getElementById(id), icons=['🥇','🥈','🥉'];
const escape = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let schools=[],events=[],selected='';
const logo = s => `<img src="${escape(s.logo)}" alt="Logo ${escape(s.name)}" loading="lazy">`;
function fallback(){document.querySelectorAll('img').forEach(img => {img.onerror=()=>{img.style.visibility='hidden';};});}
function note(e,p){return counted(e,p)?'': e.participants===null ? 'Perhitungan medali menunggu konfirmasi jumlah peserta.' : `Juara ${p} — tidak diperhitungkan dalam klasemen medali berdasarkan jumlah ${e.type==='beregu'?'regu':'peserta'}.`;}
function winner(e,w){const s=schools.find(s=>s.id===w.schoolId);return `<div class="winner"><div class="medal">${icons[w.place-1]}</div><div><strong>Juara ${w.place} — ${escape(s.name)}</strong><span>${escape(w.athlete)}</span><small>${escape(note(e,w.place))}</small></div></div>`;}
function render(){const filtered=events.filter(e=>!selected||e.sport===selected), rows=standings(filtered,schools);
  $('events').textContent=filtered.length;$('medals').textContent=rows.reduce((n,s)=>n+s.total,0);
  $('standings').innerHTML=rows.map(s=>`<tr class="${s.rank&&s.rank<=3?'top':''}"><td class="rank">${s.rank??'—'}</td><td><button class="school-button" data-school="${escape(s.id)}">${logo(s)}<span>${escape(s.name)}</span></button></td>${s.medals.map(n=>`<td>${n}</td>`).join('')}<td>${s.total}</td></tr>`).join('');
  $('results').innerHTML=filtered.map(e=>`<article class="result"><h3>${escape(e.sport)} — ${escape(e.category)}</h3><p class="metadata">${e.type==='beregu'?'Beregu':'Perorangan'}${e.participants===null?'':` · ${e.participants} ${e.type==='beregu'?'regu':'peserta'}`}${e.medalsConfirmed?' · Medali dikonfirmasi panitia':''}</p>${e.winners.map(w=>winner(e,w)).join('')}</article>`).join('')||'<p>Belum ada hasil pertandingan untuk cabang ini.</p>';
  $('notice').textContent=filtered.some(e=>e.participants===null&&!e.medalsConfirmed)?'Hasil juara sudah tersimpan. Sebagian medali menunggu konfirmasi jumlah peserta sebelum masuk klasemen.':'';fallback();
}
$('standings').addEventListener('click',e=>{const button=e.target.closest('[data-school]');if(!button)return;const s=standings(events,schools).find(s=>s.id===button.dataset.school);const awards=events.flatMap(e=>e.winners.filter(w=>w.schoolId===s.id).map(w=>`<h3>${escape(e.sport)} — ${escape(e.category)}</h3>${winner(e,w)}`));$('school-detail').innerHTML=`${logo(s).replace('<img','<img class="detail-logo"')}<h2>${escape(s.name)}</h2><p class="detail-counts">🥇 ${s.medals[0]} Emas · 🥈 ${s.medals[1]} Perak · 🥉 ${s.medals[2]} Perunggu<br><strong>Total ${s.total} medali · Semua cabang</strong></p>${awards.join('')||'<p>Belum ada hasil yang tercatat.</p>'}`;fallback();$('school-dialog').showModal();});
$('close-dialog').onclick=()=>$('school-dialog').close();$('school-dialog').addEventListener('click',e=>{if(e.target===$('school-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('filter').onchange=e=>{selected=e.target.value;render();};
try {const [schoolData,raw]=await Promise.all(['data/schools.json','data/results.json'].map(async path=>{const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error('Data tidak dapat dimuat');return response.json();}));schools=schoolData;events=normalize(raw,schools);const times=[raw.updatedAt,...events.map(e=>e.updatedAt)].map(Date.parse).filter(Number.isFinite);$('updated').textContent=times.length?'Terakhir diperbarui: '+new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Makassar'}).format(new Date(Math.max(...times)))+' WITA':'Belum ada pembaruan';$('filter').innerHTML+=[...new Set(events.map(e=>e.sport))].sort().map(s=>`<option value="${escape(s)}">${escape(s)}</option>`).join('');render();}catch(error){$('updated').textContent='Data belum dapat dimuat.';$('notice').textContent='Gagal memuat data pertandingan. Silakan muat ulang halaman.';console.error(error);}
