import assert from 'node:assert/strict';
import fs from 'node:fs';
import {counted,normalize,standings} from './logic.js';
for(const n of [0,2,3,4,5,8])for(const p of [1,2,3])assert.equal(counted({participants:n},p),n>=p+2);
assert.equal(counted({participants:null},1),false);assert.equal(counted({participants:null,medalsConfirmed:true},3),true);
const schools=JSON.parse(fs.readFileSync('data/schools.json')), raw=JSON.parse(fs.readFileSync('data/results.json'));
const events=normalize(raw,schools), rows=standings(events.filter(e=>e.sport==='Catur'),schools);
assert.equal(rows.find(s=>s.id==='mahardika').total,3);assert.equal(rows.find(s=>s.id==='sdn10').rank,1);assert.equal(rows.find(s=>s.id==='sdn16').rank,1);assert.equal(rows.find(s=>s.id==='mahardika').rank,3);assert.equal(rows.reduce((n,s)=>n+s.total,0),6);
assert.equal(normalize({results:[...raw.results,...raw.results]},schools).length,raw.results.length);
assert.ok(standings([],schools).every(s=>s.rank===null&&s.total===0));
assert.equal(normalize({results:[{...events[0],participants:'8',winners:[{place:1,schoolId:'unknown'}]}]},schools)[0].winners.length,0);
const sharedEvent={id:'test-shared',sport:'Test',category:'Putra',type:'perorangan',participants:5,sharedPlaces:[3],winners:[{place:3,schoolId:'sdn10',athlete:'A'},{place:3,schoolId:'rajyamuna',athlete:'B'},{place:3,schoolId:'sdn10',athlete:'A'}]};
const shared=normalize({results:[sharedEvent]},schools);
assert.equal(shared[0].winners.length,2);
assert.equal(standings(shared,schools).reduce((n,s)=>n+s.total,0),2);
assert.equal(normalize({results:[{...sharedEvent,sharedPlaces:[]}]},schools)[0].winners.length,1);
assert.equal(standings(normalize({results:[{...sharedEvent,participants:4}]},schools),schools).reduce((n,s)=>n+s.total,0),0);
console.log('Medal rules, confirmed results, ties, shared bronze, empty state, validation and duplicates passed.');
